### ISSUE TITLE
Support CD matrix - recall

### ISSUE THREAD

**Issue by mshubin** [astrojs/wcsjs#2]
Hello!

Currently we are using your libraries : fitsjs, sampjs and wcsjs in our project called : MIZAR (Module for Interactive visualiZation from Astronomical Repositories) in WebGL. You can check it out [here](http://demonstrator.telespazio.com/sitools/client-user/Mizar/project-index.html).

So the issue is the same as yours, opened a year ago, about rotation matrix. MIZAR allows user to extract fits data corresponding to visible tiles only from larger fits vector containing all the sky. If the camera is aligned with north there is no problem, otherwise once extraction has been done, if we drag'n'drop the result to Mizar, we observe that it was rotated, but has been declined..
I've coded some [tests](https://github.com/TPZF/RTWeb3D/tree/master/app/test): one with fits aligned with north and the other one rotated by 90°. They could be downloaded [here](https://drive.google.com/file/d/0B3lN458bn4M_SGtrMWJZaHlwV00) and [here](https://drive.google.com/file/d/0B3lN458bn4M_b0Y5b0JfX0k1R28) and must be putted in "tests" directory. (I've not commited them because of size)

If you have an idea..
Anyway, thank you for all your contributions, work perfectly!

**Comment by kapadia** [comment]
@mshubin Hi! Nice to hear that you're using these libraries. I've just redone this library so that it's a direct port of WCSLIB. As such all projections are now supported, and we no longer have an issue with the CD matrix.

Take a look at the new version, and please let me know how it come along. The API has changed a bit, but there are examples. I'm happy to take suggestions too.

Thanks for pointing me to your work. I'm going to take a closer look at it :)

**Comment by kapadia** [comment]
@mshubin Have you had a chance to try the new version yet? It should resolve any issues with the CD matrix.

**Comment by mshubin** [comment]
Yes, I've made a quick test and unfortunately, it didn't work. But with further investigation, I found that string header must be indented by function like `toHeader`. And it worked like a charm :)

The only drawback, it takes 1.3Mb even minified.. so we'll see if we introduce it in near future.
Anyway, the issue could be closed, thank you!

**Comment by kapadia** [comment]
@mshubin Glad to hear, I'll incorporate `toHeader` into the library. The large size is due to the code generated by Emscripten, not much we can do. However, you can gzip any static content (e.g. js, css) on your server, and it reduces the size of the library to ~140 kb.
