### ISSUE TITLE
wcsjs for CAR

### ISSUE THREAD

**Issue by GianniDE** [astrojs/wcsjs#3]
Hello!

Currently i'm using your libraries wcsjs.

I have a fits with GLON-CAR e GLON-CAR.
I see that your library not implement for now this value.

Can you help me for this value?

Anyway, thank you for all your contributions, work perfectly!

**Comment by kapadia** [comment]
Hi @GianniDE I've completely rewritten the library so that it's a direct port from [WCSLIB](http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/). As such, it now supports the CAR projection. It's only been tested against RA and Dec, but it should also work for GLON and GLAT.

**Comment by kapadia** [comment]
@GianniDE Have you tested your use case with the new version yet? I'm happy to test it if you send me a FITS header.

**Comment by GianniDE** [comment]
Hi, sorry but i'm in holiday :-) 
Yes i have tested new version, but i have problems, thus now i'm using the old version.

Before i'm using the old version with GLON-TAN and GLON-CAR (i have two different FITS). 
Transform the fits in jpeg and i use Kinetic in html.

I return a FITS Header with a Json, this is a example from TAN.

{"4047":{"SHAPE_FILL":false,"CDELT1":-8.8888889E-4,"GROUPING":"HIGAL","TYPECATMAP":"CATMAP","CDELT2":8.8888889E-4,"EQUINOX":2000,"CD2_2":0,"CD1_2":0,"CD1_1":0,"SHAPE_TYPE":3,"CD2_1":0,"CRVAL2":0.5257550171,"SHAPE_SIZE":12,"LONPOLE":180,"SHAPE_COLOR":"#1185DD","DECFIELD":"DEC","FILENAME":"/temp/mmc-BD191E980521F3F3E7F3B791C862EC98/HIGAL_BLUE0671p118_070_RM.jpeg","CRVAL1":66.1101660079,"ORIGINAL_SHAPE_COLOR":"#1185DD","LATPOLE":0.52575501707,"CRPIX1":1291,"NAXIS1":303,"CRPIX2":-593,"NAXIS2":303,"NAXIS":2,"RAFIELD":"RA","CTYPE1":"GLON-TAN","CTYPE2":"GLAT-TAN"}}

in this moment, with the new version, i have problem with pix2sky and sky2pix

Thanks

**Comment by kapadia** [comment]
Hi @GianniDE, can you send me the original FITS file so I can add it to the tests?

**Comment by GianniDE** [comment]
http://www.4shared.com/file/8oAc_9HEce/HIGAL_BLUE0671p118_070_RM.html
http://www.4shared.com/file/sw70rMoJce/PlanckMap_308235996_-22010959_.html

Higal is GLON-TAN 
Planck is GLON-CAR

**Comment by kapadia** [comment]
@GianniDE Do you mind sharing these files on a server that is publicly accessible. I'd rather not sign up with the service to download them.

**Comment by GianniDE** [comment]
try here : http://www.sendspace.com/file/b0gfrj     http://www.sendspace.com/file/vuvvzm

**Comment by kapadia** [comment]
@GianniDE Thanks! I added the files to the tests (68775f6c70891cffd9a4e132d642cb77a4de0268) and they appear to be working correctly. At the moment the WCS object must be initialized using a header string, but I'll add the option to initialize with a javascript object.
